/**
 * 대륙(Region) 영문명을 한국어로 매핑하는 객체
 * - REST Countries API의 region 필드를 한글로 변환할 때 사용
 */
const regionMap = {
  Asia: "아시아",
  Europe: "유럽",
  Africa: "아프리카",
  Americas: "아메리카",
  Oceania: "오세아니아",
  Antarctic: "남극",
};

/**
 * 국가 수도의 영문명을 한국어로 매핑하는 객체
 * REST Countries API에서 받아온 영문 수도 이름을
 * 사용자에게 표시할 한글 이름으로 변환하기 위해 사용
 */
const capitalKorean = {
  Avarua: "아바루아",
  Conakry: "코나크리",
  "Flying Fish Cove": "플라잉 피시 코브",
  Lomé: "로메",
  Taipei: "타이베이",
  Bishkek: "비슈케크",
  Paramaribo: "파라마리보",
  "Santo Domingo": "산토도밍고",
  "Guatemala City": "과테말라 시티",
  Algiers: "알제",
  Kyiv: "키이우",
  Basseterre: "바세테르",
  Zagreb: "자그레브",
  "Ciudad de la Paz": "시우다드 데 라 파스",
  "Panama City": "파나마 시티",
  Brussels: "브뤼셀",
  Kigali: "키갈리",
  "Port-aux-Français": "포르토프랑세",
  Praia: "프라이아",
  Seoul: "서울",
  Hagåtña: "하갓냐",
  "Andorra la Vella": "안도라 라 벨라",
  Dakar: "다카르",
  Montevideo: "몬테비데오",
  Brazzaville: "브라자빌",
  Windhoek: "빈트후크",
  Singapore: "싱가포르",
  Helsinki: "헬싱키",
  Cairo: "카이로",
  Ngerulmud: "느게룰무드",
  "Pago Pago": "파고파고",
  "Saint John's": "세인트존스",
  Victoria: "빅토리아",
  "Kuwait City": "쿠웨이트 시티",
  Athens: "아테네",
  "South Tarawa": "사우스 타라와",
  Nicosia: "니코시아",
  Bamako: "바마코",
  Hamilton: "해밀턴",
  Nuuk: "누크",
  Asmara: "아스마라",
  Dodoma: "도도마",
  Hanoi: "하노이",
  "N'Djamena": "은자메나",
  Yamoussoukro: "야무수크로",
  Tbilisi: "트빌리시",
  Douglas: "더글러스",
  "King Edward Point": "킹 에드워드 포인트",
  Sucre: "수크레",
  "Washington DC": "워싱턴 D.C.",
  Copenhagen: "코펜하겐",
  Ashgabat: "아슈하바트",
  Niamey: "니아메",
  Palikir: "팔리키르",
  "Saint Helier": "세인트 헬리어",
  "George Town": "조지타운",
  Vaduz: "파두츠",
  Sarajevo: "사라예보",
  Paris: "파리",
  Papeetē: "파페에테",
  Astana: "아스타나",
  Luanda: "루안다",
  Wellington: "웰링턴",
  "San Juan": "산후안",
  Riyadh: "리야드",
  Podgorica: "포드고리차",
  Pretoria: "프리토리아",
  Islamabad: "이슬라마바드",
  "Sri Jayawardenepura Kotte": "스리자야와르데네푸라 코테",
  Yaoundé: "야운데",
  "St. Peter Port": "세인트 피터 포트",
  Monrovia: "몬로비아",
  "Abu Dhabi": "아부다비",
  Bern: "베른",
  Budapest: "부다페스트",
  Tripoli: "트리폴리",
  "Port Vila": "포트빌라",
  "Mata-Utu": "마타우투",
  Castries: "캐스트리스",
  Bangui: "방기",
  Dushanbe: "두샨베",
  Dublin: "더블린",
  Nouméa: "누메아",
  "Sana'a": "사나",
  Tórshavn: "토르스하운",
  Havana: "하바나",
  Baku: "바쿠",
  Honiara: "호니아라",
  Kingston: "킹스턴",
  Rabat: "라바트",
  "Port of Spain": "포트오브스페인",
  Mamoudzou: "마무주",
  Alofi: "알로피",
  Belmopan: "벨모판",
  Beijing: "베이징",
  Apia: "아피아",
  "Road Town": "로드타운",
  Khartoum: "카르툼",
  Kingston: "킹스턴",
  Bratislava: "브라티슬라바",
  Gitega: "기테가",
  Majuro: "마주로",
  Vienna: "빈",
  Maputo: "마푸토",
  Kingstown: "킹스타운",
  "Port Moresby": "포트모르즈비",
  Ankara: "앙카라",
  Pristina: "프리스티나",
  "St. George's": "세인트조지스",
  "Phnom Penh": "프놈펜",
  Lisbon: "리스본",
  London: "런던",
  Abuja: "아부자",
  "The Valley": "더 밸리",
  Saipan: "사이판",
  Jerusalem: "예루살렘",
  Cayenne: "카옌",
  Beirut: "베이루트",
  Tokyo: "도쿄",
  Banjul: "반줄",
  Marigot: "마리고",
  Bissau: "비사우",
  Vientiane: "비엔티안",
  Skopje: "스코페",
  Doha: "도하",
  Lusaka: "루사카",
  Bridgetown: "브리지타운",
  "Vatican City": "바티칸 시티",
  Rome: "로마",
  Moroni: "모로니",
  Tirana: "티라나",
  Gibraltar: "지브롤터",
  "Ulan Bator": "울란바토르",
  "Nuku'alofa": "누쿠알로파",
  Antananarivo: "안타나나리보",
  "Saint-Pierre": "생피에르",
  Jamestown: "제임스타운",
  Monaco: "모나코",
  Brasília: "브라질리아",
  Canberra: "캔버라",
  Georgetown: "조지타운",
  Ljubljana: "류블랴나",
  "City of San Marino": "산마리노 시",
  Fakaofo: "파카오포",
  Ramallah: "라말라",
  Thimphu: "팀부",
  Philipsburg: "필립스버그",
  Manila: "마닐라",
  Santiago: "산티아고",
  "Fort-de-France": "포르드프랑스",
  "Port-au-Prince": "포르토프랭스",
  "São Tomé": "상투메",
  "Port Louis": "포트루이스",
  Manama: "마나마",
  "Mexico City": "멕시코시티",
  Adamstown: "애덤스타운",
  "Buenos Aires": "부에노스아이레스",
  Kathmandu: "카트만두",
  Stockholm: "스톡홀름",
  Freetown: "프리타운",
  Mbabane: "음바바네",
  Madrid: "마드리드",
  Bogotá: "보고타",
  "Cockburn Town": "콕번 타운",
  Djibouti: "지부티",
  Yaren: "야렌",
  "San Salvador": "산살바도르",
  Mariehamn: "마리에함",
  "Basse-Terre": "바스테르",
  Tegucigalpa: "테구시갈파",
  Nairobi: "나이로비",
  Valletta: "발레타",
  Riga: "리가",
  Libreville: "리브르빌",
  "City of Victoria": "빅토리아 시",
  Longyearbyen: "롱이어비엔",
  Funafuti: "푸나푸티",
  Dili: "딜리",
  "El Aaiún": "엘아이운",
  Maseru: "마세루",
  "Washington, D.C.": "워싱턴 D.C.",
  Bangkok: "방콕",
  "Diego Garcia": "디에고 가르시아",
  "New Delhi": "뉴델리",
  Vilnius: "빌니우스",
  Plymouth: "플리머스",
  Harare: "하라레",
  Stanley: "스탠리",
  Malé: "말레",
  Tunis: "튀니스",
  Tallinn: "탈린",
  Dhaka: "다카",
  Tashkent: "타슈켄트",
  Accra: "아크라",
  Oslo: "오슬로",
  Mogadishu: "모가디슈",
  Nassau: "나소",
  Muscat: "무스카트",
  Luxembourg: "룩셈부르크",
  Baghdad: "바그다드",
  "Charlotte Amalie": "샬럿 아말리에",
  Nouakchott: "누악쇼트",
  Ottawa: "오타와",
  Naypyidaw: "네피도",
  "Kuala Lumpur": "쿠알라룸푸르",
  "West Island": "웨스트 아일랜드",
  Kralendijk: "크랄렌다이크",
  Kampala: "캄팔라",
  Tehran: "테헤란",
  Willemstad: "빌렘스타트",
  Bucharest: "부쿠레슈티",
  Damascus: "다마스쿠스",
  Suva: "수바",
  Oranjestad: "오란예스타트",
  Amsterdam: "암스테르담",
  Lima: "리마",
  "Saint-Denis": "생드니",
  Gaborone: "가보로네",
  Kabul: "카불",
  Belgrade: "베오그라드",
  Prague: "프라하",
  Roseau: "로조",
  Warsaw: "바르샤바",
  "Porto-Novo": "포르토노보",
  Chișinău: "키시나우",
  Moscow: "모스크바",
  Gustavia: "구스타비아",
  Jakarta: "자카르타",
  Managua: "마나과",
  Yerevan: "예레반",
  Minsk: "민스크",
  "Addis Ababa": "아디스아바바",
  "San José": "산호세",
  Amman: "암만",
  Berlin: "베를린",
  Quito: "키토",
  Pyongyang: "평양",
  Reykjavik: "레이캬비크",
  Juba: "주바",
  Lilongwe: "릴롱궤",
  Ouagadougou: "와가두구",
  Kinshasa: "킨샤사",
  Caracas: "카라카스",
  "Bandar Seri Begawan": "반다르 세리 베가완",
  Asunción: "아순시온",
  Sofia: "소피아",
};

const languageMap = {
  Afrikaans: "아프리칸스어",
  Albanian: "알바니아어",
  Amharic: "암하라어",
  Arabic: "아랍어",
  Aramaic: "아람어",
  Armenian: "아르메니아어",
  Aymara: "아이마라어",
  Azerbaijani: "아제르바이잔어",
  Basque: "바스크어",
  Belarusian: "벨라루스어",
  "Belizean Creole": "벨리즈 크리올어",
  Bengali: "벵골어",
  Berber: "베르베르어",
  Bislama: "비스라마어",
  Bosnian: "보스니아어",
  Bulgarian: "불가리아어",
  Burmese: "버마어",
  Carolinian: "캐롤라인어",
  Catalan: "카탈루냐어",
  Chamorro: "차모로어",
  Chewa: "체와어",
  Chibarwe: "치바르바어",
  Comorian: "코모로어",
  "Cook Islands Māori": "쿡 제도 마오리어",
  Croatian: "크로아티아어",
  Czech: "체코어",
  Danish: "덴마크어",
  Dari: "다리어",
  Dutch: "네덜란드어",
  Dzongkha: "종카어",
  Estonian: "에스토니아어",
  Faroese: "페로어",
  "Fiji Hindi": "피지 힌디어",
  Fijian: "피지어",
  Filipino: "필리핀어",
  Finnish: "핀란드어",
  Galician: "갈리시아어",
  Georgian: "조지아어",
  Gilbertese: "길버트어",
  Greek: "그리스어",
  Greenlandic: "그린란드어",
  Guaraní: "과라니어",
  Guernésiais: "건지어",
  "Haitian Creole": "아이티 크리올어",
  Hassaniya: "하사니야어",
  Hebrew: "히브리어",
  Herero: "헤레로어",
  Hindi: "힌디어",
  "Hiri Motu": "히리 모투어",
  Hungarian: "헝가리어",
  Icelandic: "아이슬란드어",
  Indonesian: "인도네시아어",
  Irish: "아일랜드어",
  Italian: "이탈리아어",
  "Jamaican Patois": "자메이카 파토이스",
  Jèrriais: "저지어",
  Kalanga: "칼랑가어",
  Kazakh: "카자흐어",
  Khmer: "크메르어",
  Khoekhoe: "코이코어",
  Khoisan: "코이산어",
  Kikongo: "키콩고어",
  Kinyarwanda: "키냐르완다어",
  Kirundi: "키룬디어",
  Kwangali: "콰낭알리어",
  Kyrgyz: "키르기스어",
  Lao: "라오어",
  Latin: "라틴어",
  Latvian: "라트비아어",
  Lingala: "링갈라어",
  Lithuanian: "리투아니아어",
  Lozi: "로지어",
  Luxembourgish: "룩셈부르크어",
  Macedonian: "마케도니아어",
  Malagasy: "말라가시어",
  Malay: "말레이어",
  Maldivian: "디베히어",
  Maltese: "몰타어",
  Manx: "맨스어",
  Māori: "마오리어",
  Marshallese: "마셜어",
  "Mauritian Creole": "모리셔스 크리올어",
  Mongolian: "몽골어",
  Montenegrin: "몬테네그로어",
  Nauru: "나우루어",
  Ndau: "은다우어",
  Ndonga: "은동가어",
  Nepali: "네팔어",
  "New Zealand Sign Language": "뉴질랜드 수화",
  Niuean: "니우에어",
  Norfuk: "노퍽어",
  "Northern Ndebele": "북은데벨레어",
  "Northern Sotho": "북소토어",
  Norwegian: "노르웨이어",
  "Norwegian Bokmål": "노르웨이어 (보크몰)",
  "Norwegian Nynorsk": "노르웨이어 (뉘노르스크)",
  Palauan: "팔라우어",
  Papiamento: "파피아멘토어",
  Pashto: "파슈토어",
  "Persian (Farsi)": "페르시아어",
  Polish: "폴란드어",
  Portuguese: "포르투갈어",
  Quechua: "케추아어",
  Romanian: "루마니아어",
  Romansh: "로만슈어",
  Russian: "러시아어",
  Sami: "사미어",
  Samoan: "사모아어",
  Sango: "산고어",
  Serbian: "세르비아어",
  "Seychellois Creole": "세이셸 크리올어",
  Shona: "쇼나어",
  Sinhala: "싱할라어",
  Slovak: "슬로바키아어",
  Slovene: "슬로베니아어",
  Somali: "소말리아어",
  Sorani: "소라니 쿠르드어",
  Sotho: "소토어",
  "Southern Ndebele": "남은데벨레어",
  "Southern Sotho": "남소토어",
  Swahili: "스와힐리어",
  Swazi: "스와지어",
  Swedish: "스웨덴어",
  "Swiss German": "스위스 독일어",
  Tajik: "타지크어",
  Tamil: "타밀어",
  Tetum: "테툼어",
  Thai: "태국어",
  Tigrinya: "티그리냐어",
  "Tok Pisin": "톡 피신어",
  Tokelauan: "토켈라우어",
  Tonga: "통가어",
  Tongan: "통가어",
  Tshiluba: "칠루바어",
  Tsonga: "총가어",
  Tswana: "츠와나어",
  Turkish: "터키어",
  Turkmen: "투르크멘어",
  Tuvaluan: "투발루어",
  Ukrainian: "우크라이나어",
  "Upper Guinea Creole": "어퍼 기니 크리올어",
  Urdu: "우르두어",
  Uzbek: "우즈베크어",
  Venda: "벤다어",
  Vietnamese: "베트남어",
  Xhosa: "코사어",
  "Zimbabwean Sign Language": "짐바브웨 수화",
  Zulu: "줄루어",
  German: "독일어",
  Spanish: "스페인어",
  English: "영어",
  Japanese: "일본어",
  Chinese: "중국어",
  French: "프랑스어",
  Korean: "한국어",
};
